### PR TITLE
console: Don't return error for non-existing files

### LINKED ISSUE #84: Regression: NewFileSerialPortAttachment() no longer create log files
When using NewFileSerialPortAttachment(), the virtualization framework will create the log file if it does not exist yet.
Commit https://github.com/Code-Hex/vz/commit/117c12a5820925a3e7117b1a547af37ef845f085 added a file existence check to this API, which is incorrect. An error is now returned even if NewFileSerialPortAttachment() would create the file.
If a directory in the path is non-existent, NewFileSerialPortAttachment() returns an error, it does not throw an exception, so the file existence check is also not needed in this case.

### PR DESCRIPTION
**Pull request by cfergeau**
When using NewFileSerialPortAttachment(), the virtualization framework will
create the log file if it does not exist yet.
commit 117c12a added a file existence check to this API, which is incorrect.

Fixes #84

### CODE REVIEW

**Comment by cfergeau** [comment]
The failure on the macOS11 builders is not strictly related to this PR 
```
            issues_test.go:112: want underlying error "file does not exist" but got "unsupported macOS version"
```

**Comment by cfergeau** [comment]
Probably not the best fix, but good enough to get the tests to pass ;)

File: console.go [hunk 1]
```diff
@@ -78,19 +78,16 @@ type FileSerialPortAttachment struct {
 // NewFileSerialPortAttachment initialize the FileSerialPortAttachment from a path of a file.
 // If error is not nil, used to report errors if intialization fails.
 //
-//   - path of the file for the attachment on the local file system.
-//   - shouldAppend True if the file should be opened in append mode, false otherwise.
-//     When a file is opened in append mode, writing to that file will append to the end of it.
+// - path of the file for the attachment on the local file system.
+// - shouldAppend True if the file should be opened in append mode, false otherwise.
+//    When a file is opened in append mode, writing to that file will append to the end of it.
```
Comment (Code-Hex) [inline console.go:83]: Could you use go1.19 gofmt?

**Comment by Code-Hex** [comment]
@cfergeau Create the issue first, as described in the contribution guide.
I will not review anything that does not comply with the rules.

> Ensure the PR description clearly describes the problem and solution. Must be included the relevant issue number.

https://github.com/Code-Hex/vz/blob/master/CONTRIBUTING.md

**Comment by cfergeau** [comment]
> @cfergeau Create the issue first, as described in the contribution guide. I will not review anything that does not comply with the rules. (I close your PR)
> 
> > Ensure the PR description clearly describes the problem and solution. Must be included the relevant issue number.
> 
> https://github.com/Code-Hex/vz/blob/master/CONTRIBUTING.md

This was missing from some of your recent commits. I assumed this was no longer a strict requirement.

File: console.go (hunk 1 above)
Comment (cfergeau) [reply console.go]: Fixed.

**Review by Code-Hex — APPROVED** [review]
Thanks
